package parser

type Token struct {
	value     string
	typ       TokenType
	endOffset int
}

type TokenType string

const (
	// common
	KeywordSchema     TokenType = "schema"
	KeywordDatabase   TokenType = "database"
	KeywordTable      TokenType = "table"
	KeywordColumn     TokenType = "column"
	KeywordView       TokenType = "view"
	KeywordIndex      TokenType = "index"
	KeywordTrigger    TokenType = "trigger"
	KeywordProcedure  TokenType = "procedure"
	KeywordTablespace TokenType = "tablespace"
	KeywordFunction   TokenType = "function"
	KeywordSequence   TokenType = "sequence"
	KeywordCursor     TokenType = "cursor"
	KeywordFrom       TokenType = "from"
	KeywordTo         TokenType = "to"
	KeywordOf         TokenType = "of"
	KeywordIf         TokenType = "if"
	KeywordOn         TokenType = "on"
	KeywordFor        TokenType = "for"
	KeywordWhile      TokenType = "while"
	KeywordDo         TokenType = "do"
	KeywordNo         TokenType = "no"
	KeywordBy         TokenType = "by"
	KeywordWith       TokenType = "with"
	KeywordWithout    TokenType = "without"
	KeywordTrue       TokenType = "true"
	KeywordFalse      TokenType = "false"
	KeywordTemporary  TokenType = "temporary"
	KeywordTemp       TokenType = "temp"
	KeywordComment    TokenType = "comment"

	// create
	KeywordCreate    TokenType = "create"
	KeywordReplace   TokenType = "replace"
	KeywordBefore    TokenType = "before"
	KeywordAfter     TokenType = "after"
	KeywordInstead   TokenType = "instead"
	KeywordEach      TokenType = "each"
	KeywordRow       TokenType = "row"
	KeywordStatement TokenType = "statement"
	KeywordExecute   TokenType = "execute"
	KeywordBitmap    TokenType = "bitmap"
	KeywordNosort    TokenType = "nosort"
	KeywordReverse   TokenType = "reverse"
	KeywordCompile   TokenType = "compile"

	// alter
	KeywordAlter      TokenType = "alter"
	KeywordAdd        TokenType = "add"
	KeywordModify     TokenType = "modify"
	KeywordRename     TokenType = "rename"
	KeywordEnable     TokenType = "enable"
	KeywordDisable    TokenType = "disable"
	KeywordValidate   TokenType = "validate"
	KeywordUser       TokenType = "user"
	KeywordIdentified TokenType = "identified"
	KeywordTruncate   TokenType = "truncate"
	KeywordDrop       TokenType = "drop"
	KeywordCascade    TokenType = "cascade"
	KeywordInsert     TokenType = "insert"
	KeywordInto       TokenType = "into"
	KeywordValues     TokenType = "values"
	KeywordUpdate     TokenType = "update"
	KeywordSet        TokenType = "set"
	KeywordDelete     TokenType = "delete"

	KeywordSelect   TokenType = "select"
	KeywordDistinct TokenType = "distinct"
	KeywordAs       TokenType = "as"
	KeywordCase     TokenType = "case"
	KeywordWhen     TokenType = "when"
	KeywordElse     TokenType = "else"
	KeywordThen     TokenType = "then"
	KeywordEnd      TokenType = "end"
	KeywordLeft     TokenType = "left"
	KeywordRight    TokenType = "right"
	KeywordFull     TokenType = "full"
	KeywordInner    TokenType = "inner"
	KeywordOuter    TokenType = "outer"
	KeywordCross    TokenType = "cross"
	KeywordJoin     TokenType = "join"
	KeywordUse      TokenType = "use"
	KeywordUsing    TokenType = "using"
	KeywordNatural  TokenType = "natural"
	KeywordWhere    TokenType = "where"
	KeywordOrder    TokenType = "order"
	KeywordAsc      TokenType = "asc"
	KeywordDesc     TokenType = "desc"
	KeywordGroup    TokenType = "group"
	KeywordHaving   TokenType = "having"
	KeywordUnion    TokenType = "union"

	// others
	KeywordDeclare   TokenType = "declare"
	KeywordGrant     TokenType = "grant"
	KeywordFetch     TokenType = "fetch"
	KeywordRevoke    TokenType = "revoke"
	KeywordClose     TokenType = "close"
	KeywordCast      TokenType = "cast"
	KeywordNew       TokenType = "new"
	KeywordEscape    TokenType = "escape"
	KeywordLock      TokenType = "lock"
	KeywordSome      TokenType = "some"
	KeywordLeave     TokenType = "leave"
	KeywordIterate   TokenType = "iterate"
	KeywordRepeat    TokenType = "repeat"
	KeywordUntil     TokenType = "until"
	KeywordOpen      TokenType = "open"
	KeywordOut       TokenType = "out"
	KeywordInout     TokenType = "inout"
	KeywordOver      TokenType = "over"
	KeywordAdvise    TokenType = "advise"
	KeywordSiblings  TokenType = "siblings"
	KeywordLoop      TokenType = "loop"
	KeywordExplain   TokenType = "explain"
	KeywordDefault   TokenType = "default"
	KeywordExcept    TokenType = "except"
	KeywordIntersect TokenType = "intersect"
	KeywordMinus     TokenType = "minus"
	KeywordPassword  TokenType = "password"
	KeywordLocal     TokenType = "local"
	KeywordGlobal    TokenType = "global"
	KeywordStorage   TokenType = "storage"
	KeywordData      TokenType = "data"
	KeywordCoalesce  TokenType = "coalesce"

	// types
	KeywordChar      TokenType = "char"
	KeywordCharacter TokenType = "character"
	KeywordVarying   TokenType = "varying"
	KeywordVarchar   TokenType = "varchar"
	KeywordVarchar2  TokenType = "varchar2"
	KeywordInteger   TokenType = "integer"
	KeywordInt       TokenType = "int"
	KeywordSmallint  TokenType = "smallint"
	KeywordDecimal   TokenType = "decimal"
	KeywordDec       TokenType = "dec"
	KeywordNumeric   TokenType = "numeric"
	KeywordFloat     TokenType = "float"
	KeywordReal      TokenType = "real"
	// KeywordDouble    TokenType = "double"
	KeywordPrecision TokenType = "precision"
	KeywordDate      TokenType = "date"
	KeywordTime      TokenType = "time"
	KeywordInterval  TokenType = "interval"
	KeywordBoolean   TokenType = "boolean"
	KeywordBlob      TokenType = "blob"

	// Conditionals
	KeywordAnd     TokenType = "and"
	KeywordOr      TokenType = "or"
	KeywordXor     TokenType = "xor"
	KeywordIs      TokenType = "is"
	KeywordNot     TokenType = "not"
	KeywordNull    TokenType = "null"
	KeywordIn      TokenType = "in"
	KeywordBetween TokenType = "between"
	KeywordLike    TokenType = "like"
	KeywordAny     TokenType = "any"
	KeywordAll     TokenType = "all"
	KeywordExists  TokenType = "exists"

	// functions
	KeywordAvg        TokenType = "avg"
	KeywordMax        TokenType = "max"
	KeywordMin        TokenType = "min"
	KeywordSum        TokenType = "sum"
	KeywordCount      TokenType = "count"
	KeywordGreatest   TokenType = "greatest"
	KeywordLeast      TokenType = "least"
	KeywordRound      TokenType = "round"
	KeywordTrunc      TokenType = "trunc"
	KeywordPosition   TokenType = "position"
	KeywordExtract    TokenType = "extract"
	KeywordLength     TokenType = "length"
	KeywordCharLength TokenType = "charlength"
	KeywordSubstring  TokenType = "substring"
	KeywordSubstr     TokenType = "substr"
	KeywordInstr      TokenType = "instr"
	KeywordInitcap    TokenType = "initcap"
	KeywordUpper      TokenType = "upper"
	KeywordLower      TokenType = "lower"
	KeywordTrim       TokenType = "trim"
	KeywordLtrim      TokenType = "ltrim"
	KeywordRtrim      TokenType = "rtrim"
	KeywordBoth       TokenType = "both"
	KeywordLeading    TokenType = "leading"
	KeywordTrailing   TokenType = "trailing"
	KeywordTranslate  TokenType = "translate"
	KeywordConvert    TokenType = "convert"
	KeywordLPAD       TokenType = "lpad"
	KeywordRPAD       TokenType = "rpad"
	KeywordDecode     TokenType = "decode"
	KeywordNvl        TokenType = "nvl"

	// Constraints
	KeywordConstraint TokenType = "constraint"
	KeywordUnique     TokenType = "unique"
	KeywordPrimary    TokenType = "primary"
	KeywordForeign    TokenType = "foreign"
	KeywordKey        TokenType = "key"
	KeywordCheck      TokenType = "check"
	KeywordReferences TokenType = "references"

	// Symbol
	SymbolPlus         TokenType = "+"
	SymbolSub          TokenType = "-"
	SymbolStar         TokenType = "*"
	SymbolSlash        TokenType = "/"
	SymbolEq           TokenType = "="
	SymbolBangEq       TokenType = "!="
	SymbolGt           TokenType = ">"
	SymbolGtEq         TokenType = ">="
	SymbolLt           TokenType = "<"
	SymbolLtEq         TokenType = "<="
	SymbolLeftParen    TokenType = "("
	SymbolRightParen   TokenType = ")"
	SymbolLeftBrace    TokenType = "{"
	SymbolRightBrace   TokenType = "}"
	SymbolLeftBracket  TokenType = "["
	SymbolRightBracket TokenType = "]"
	SymbolComma        TokenType = ","
	SymbolDot          TokenType = "."
	SymbolDoubleDot    TokenType = ".."
	SymbolSemicolon    TokenType = ";"
	SymbolColon        TokenType = ":"
	SymbolPercent      TokenType = "%"
	SymbolAmp          TokenType = "&"
	SymbolBar          TokenType = "|"

	// Literal
	LiteralIdentifier TokenType = "identifier"
	LiteralString     TokenType = "string"
	LiteralLong       TokenType = "long"
	LiteralDouble     TokenType = "double"
)
